local ensure_installed = {
  "bash-language-server",
  "clangd",
  "css-lsp",
  "dockerfile-language-server",
  "eslint-lsp",
  "golangci-lint",
  "golangci-lint-langserver",
  "gofumpt",
  "gopls",
  "helm-ls",
  "html-lsp",
  "jdtls",
  "jq",
  "json-lsp",
  "ltex-ls",
  "lua-language-server",
  "nil",
  "pgformatter",
  "prettier",
  "rust-analyzer",
  "shfmt",
  "stylua",
  "terraform-ls",
  "typescript-language-server",
  "yaml-language-server",
  "zls",
}
require("mason").setup()
require("mason-tool-installer").setup({
  ensure_installed = ensure_installed,
  auto_update = false,
  run_on_start = true,
  start_delay = 3000,
  debounce_hours = 12,
})
