[colors]
[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.normal]
black = "#1e2127"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[env]
TERM = "alacritty"

[font]
size = 12
[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
decorations = "transparent"
dynamic_padding = true
dynamic_title = true
option_as_alt = "Both"

[window.padding]
x = 5
y = 25
