# Configuration for Alacritty, the GPU enhanced terminal emulator.
env:
  TERM: alacritty
  # TERM: xterm-256color

window:
  decorations: transparent
  dynamic_padding: true
  padding:
    x: 5
    y: 25

  dynamic_title: true
  option_as_alt: Both

scrolling:
  history: 10000

font:
  normal:
    family: Inconsolata LGC Nerd Font
    style: Regular

  bold:
    family: Inconsolata LGC Nerd Font
    style: Bold

  italic:
    family: Inconsolata LGC Nerd Font
    style: Italic

  bold_italic:
    family: Inconsolata LGC Nerd Font
    style: Bold Italic

  size: 12.0

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: "0x1e2127"
    foreground: "0xabb2bf"

  # Normal colors
  normal:
    black: "0x1e2127"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xabb2bf"

  # Bright colors
  bright:
    black: "0x5c6370"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xffffff"

live_config_reload: true
