live_config_reload = true

# Colors (One Dark)
[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"

[env]
TERM = "alacritty"
#TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Inconsolata LGC Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Inconsolata LGC Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Inconsolata LGC Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata LGC Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[window]
decorations = "transparent"
dynamic_padding = true
dynamic_title = true
option_as_alt = "Both"

[window.padding]
x = 5
y = 25
