macos_option_as_alt left
macos_titlebar_color background

font_family JetBrains Mono
bold_font JetBrains Mono Bold
italic_font JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic

font_size 12.0

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+0 goto_tab 10

tab_bar_edge top
tab_bar_style separator
tab_separator " │ "
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title} #{index}"

foreground #abb2bf
background #282c34

color0 #1e2127
color1 #e06c75
color2 #98c379
color3 #d19a66
color4 #61afef
color5 #c678dd
color6 #56b6c2
color7 #abb2bf
color8 #5c6370
color9 #e06c75
color10 #98c379
color11 #d19a66
color12 #61afef
color13 #c678dd
color14 #56b6c2
color15 #ffffff

selection_background #abb2bf
selection_foreground #282c34

url_color #565c64
cursor #abb2bf
active_border_color #545862
inactive_border_color #353b45

active_tab_foreground #abb2bf
active_tab_background #282c34
inactive_tab_background #353b45
inactive_tab_foreground #565c64
tab_bar_background #353b45
