#!/bin/bash

# source this script to launch gpg-agent and set up SSH_AUTH_SOCK
# use gpg-agent for ssh
# https://www.gnupg.org/documentation/manuals/gnupg/Agent-Examples.html#Agent-Examples
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
  export SSH_AUTH_SOCK
fi
GPG_TTY="$(tty)"
export GPG_TTY
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye >/dev/null
