require("config.options")
require("config.keymaps")

require("user.autocommands")
require("user.lsp")

-- Add local plugin rtp path.
vim.opt.runtimepath:append("~/.local/share/nvim/site/pack/*/start/*")
vim.opt.runtimepath:append("~/.local/share/nvim/site/plugin/*")

vim.pack.add({
  { src = "https://github.com/b0o/SchemaStore.nvim/" },
  { src = "https://github.com/yetone/avante.nvim" },
  { src = "https://github.com/saghen/blink.cmp" },
  { src = "https://github.com/moyiz/blink-emoji.nvim/" },
  { src = "https://github.com/akinsho/bufferline.nvim/" },
  { src = "https://git.sr.ht/~p00f/clangd_extensions.nvim" },
  { src = "https://github.com/stevearc/conform.nvim/" },
  { src = "https://github.com/zbirenbaum/copilot.lua/" },
  { src = "https://github.com/nvimdev/dashboard-nvim/" },
  { src = "https://github.com/Bekaboo/dropbar.nvim/" },
  { src = "https://github.com/rafamadriz/friendly-snippets/" },
  { src = "https://github.com/shumphrey/fugitive-gitlab.vim/" },
  { src = "https://github.com/akinsho/git-conflict.nvim/" },
  { src = "https://github.com/lewis6991/gitsigns.nvim" },
  { src = "https://github.com/calops/hmts.nvim/" },
  { src = "https://github.com/HakonHarnes/img-clip.nvim/" },
  { src = "https://github.com/lukas-reineke/indent-blankline.nvim/" },
  { src = "https://github.com/onsails/lspkind.nvim/" },
  { src = "https://github.com/nvim-lualine/lualine.nvim" },
  { src = "https://github.com/iamcco/markdown-preview.nvim/" },
  { src = "https://github.com/nvim-mini/mini.nvim/" },
  { src = "https://github.com/nvim-neo-tree/neo-tree.nvim/" },
  { src = "https://github.com/folke/neoconf.nvim/" },
  { src = "https://github.com/folke/neodev.nvim/" },
  { src = "https://github.com/folke/noice.nvim/" },
  { src = "https://github.com/MunifTanjim/nui.nvim" },
  { src = "https://github.com/catgoose/nvim-colorizer.lua/" },
  { src = "https://github.com/neovim/nvim-lspconfig/" },
  { src = "https://github.com/rcarriga/nvim-notify/" },
  { src = "https://github.com/garymjr/nvim-snippets/" },
  { src = "https://github.com/nvim-pack/nvim-spectre/" },
  { src = "https://github.com/kylechui/nvim-surround/" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter-context/" },
  { src = "https://github.com/RRethy/nvim-treesitter-endwise/" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects/" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter/" },
  { src = "https://github.com/windwp/nvim-ts-autotag/" },
  { src = "https://github.com/joosepalviste/nvim-ts-context-commentstring/" },
  { src = "https://github.com/nvim-tree/nvim-web-devicons" },
  { src = "https://github.com/navarasu/onedark.nvim/" },
  { src = "https://github.com/nvim-lua/plenary.nvim" },
  { src = "https://github.com/MeanderingProgrammer/render-markdown.nvim/" },
  { src = "https://github.com/folke/snacks.nvim/" },
  { src = "https://github.com/nvim-telescope/telescope-fzf-native.nvim/" },
  { src = "https://github.com/nvim-telescope/telescope.nvim" },
  { src = "https://github.com/nvim-telescope/telescope-project.nvim/" },
  { src = "https://github.com/folke/todo-comments.nvim/" },
  { src = "https://github.com/folke/trouble.nvim/" },
  { src = "https://github.com/folke/ts-comments.nvim/" },
  { src = "https://github.com/mbbill/undotree/" },
  { src = "https://github.com/tpope/vim-abolish/" },
  { src = "https://github.com/tommcdo/vim-fubitive/" },
  { src = "https://github.com/tpope/vim-fugitive/" },
  { src = "https://github.com/jamessan/vim-gnupg/" },
  { src = "https://github.com/RRethy/vim-illuminate/" },
  { src = "https://github.com/tpope/vim-repeat/" },
  { src = "https://github.com/tpope/vim-rhubarb/" },
  { src = "https://github.com/tpope/vim-sleuth/" },
  { src = "https://github.com/tpope/vim-speeddating/" },
  { src = "https://github.com/dstein64/vim-startuptime/" },
  { src = "https://github.com/christoomey/vim-tmux-navigator/" },
  { src = "https://github.com/tpope/vim-unimpaired/" },
  { src = "https://github.com/tpope/vim-vinegar/" },
  { src = "https://github.com/folke/which-key.nvim/" },
  { src = "https://github.com/folke/zen-mode.nvim/" },
})
